services:
  - type: web
    name: spacecards-loyalty
    env: node
    buildCommand: ./build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOYVERSE_TOKEN
        value: 68c66646696548af983a2a0b8e64c2ec
      - key: STORE_ID
        value: b7e82499-21b0-4e9d-aae5-16d90693c77a
      - key: WELCOME_POINTS
        value: 100
